version: '3.7'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - ../temp/db/:/var/lib/postgresql/data/

  app:
    build:
      context: .
    ports:
      - "3001:3001"
    volumes:
      - .:/chatter
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/chatter
      REDIS_URL: "redis://redis:6379/1"
    tty: true
